from BlogFront import BlogFront
from BlogHandler import BlogHandler
from Deleted import Deleted
from EditComment import EditComment
from EditPost import EditPost
from LikePost import LikePost
from Login import Login
from Logout import Logout
from MainPage import MainPage
from NewComment import NewComment
from NewPost import NewPost
from PostPage import PostPage
from Register import Register
from Signup import Signup
from Welcome import Welcome
